#!/usr/bin/env ansible-playbook

---
- name: Print something
  hosts: applicationservers
  gather_facts: no

  tasks:
    - name: Print hello world
      ansible.builtin.debug:
        msg: "Hello World!"
